#include <stddef.h> for NULL.
../../../../vice/src/arch/sdl/menu_c64dtvhw.c: In function 'custom_DTVModel_callback':
../../../../vice/src/arch/sdl/menu_c64dtvhw.c:61:12: error: 'NULL' undeclared (first use in this function)
     return NULL;
            ^~~~
compilation terminated due to -Wfatal-errors.


In file included from ../../../../vice/src/arch/sdl/menu_common.h:38:0,
                 from ../../../../vice/src/arch/sdl/menu_jam.c:30:
../../../../vice/src/arch/sdl/uimenu.h:90:29: error: 'NULL' undeclared here (not in a function)
 #define SDL_MENU_LIST_END { NULL, MENU_ENTRY_TEXT, NULL, NULL }
                             ^
../../../../vice/src/arch/sdl/menu_jam.c:42:5: note: in expansion of macro 'SDL_MENU_LIST_END'
     SDL_MENU_LIST_END
     ^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.